# Generated by Django 2.2.2 on 2021-03-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(choices=[(1, '有效'), (0, '已删除')], default=1, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='分组名称')),
            ],
            options={
                'verbose_name': '3.分组表',
                'verbose_name_plural': '3.分组表',
                'db_table': 'drfRBAC_Group',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(choices=[(1, '有效'), (0, '已删除')], default=1, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='身份名称')),
                ('Group', models.ForeignKey(blank=True, db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Identity', to='RBAC.Group', verbose_name='分组')),
            ],
            options={
                'verbose_name': '2.身份表',
                'verbose_name_plural': '2.身份表',
                'db_table': 'drfRBAC_Identity',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(choices=[(1, '有效'), (0, '已删除')], default=1, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('name', models.CharField(max_length=15, verbose_name='权限名称')),
                ('codeName', models.CharField(max_length=30, verbose_name='权限代码')),
            ],
            options={
                'verbose_name': '4.权限表',
                'verbose_name_plural': '4.权限表',
                'db_table': 'drfRBAC_Permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(choices=[(1, '有效'), (0, '已删除')], default=1, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('nickName', models.CharField(max_length=10, verbose_name='名字')),
                ('account', models.CharField(max_length=20, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
            options={
                'verbose_name': '1.用户表',
                'verbose_name_plural': '1.用户表',
                'db_table': 'drfRBAC_User',
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(choices=[(1, '有效'), (0, '已删除')], default=1, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('Permissions', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserPermissions', to='RBAC.Permissions', verbose_name='权限')),
                ('User', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserPermissions', to='RBAC.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '6.用户/权限关系表',
                'verbose_name_plural': '6.用户/权限关系表',
                'db_table': 'drfRBAC_User_Permissions',
            },
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(choices=[(1, '有效'), (0, '已删除')], default=1, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('User', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserIdentity', to='RBAC.User', verbose_name='用户')),
                ('identity', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserIdentity', to='RBAC.Identity', verbose_name='身份')),
            ],
            options={
                'verbose_name': '5.用户/身份关系表',
                'verbose_name_plural': '5.用户/身份关系表',
                'db_table': 'drfRBAC_User_Identity',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='Permissions',
            field=models.ManyToManyField(related_name='User', through='RBAC.UserPermissions', to='RBAC.Permissions', verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.ManyToManyField(related_name='User', through='RBAC.UserIdentity', to='RBAC.Identity', verbose_name='身份'),
        ),
        migrations.CreateModel(
            name='IdentityPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.BooleanField(choices=[(1, '有效'), (0, '已删除')], default=1, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, verbose_name='数据修改时间')),
                ('Permissions', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='IdentityPermissions', to='RBAC.Permissions', verbose_name='权限')),
                ('identity', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='IdentityPermissions', to='RBAC.Identity', verbose_name='身份')),
            ],
            options={
                'verbose_name': '7.身份/权限关系表',
                'verbose_name_plural': '7.身份/权限关系表',
                'db_table': 'drfRBAC_identity_permissions',
            },
        ),
        migrations.AddField(
            model_name='identity',
            name='Permissions',
            field=models.ManyToManyField(related_name='Identity', through='RBAC.IdentityPermissions', to='RBAC.Permissions', verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='identity',
            name='superior',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lowerLevel', to='RBAC.Identity', verbose_name='上级'),
        ),
    ]
