# Generated by Django 2.2.2 on 2021-03-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='Group',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Identity', to='RBAC.Group', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='superior',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lowerLevel', to='RBAC.Identity', verbose_name='上级'),
        ),
        migrations.AlterField(
            model_name='identitypermissions',
            name='Permissions',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='IdentityPermissions', to='RBAC.Permissions', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='identitypermissions',
            name='identity',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='IdentityPermissions', to='RBAC.Identity', verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='useridentity',
            name='User',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserIdentity', to='RBAC.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='useridentity',
            name='identity',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserIdentity', to='RBAC.Identity', verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='Permissions',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserPermissions', to='RBAC.Permissions', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='User',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='UserPermissions', to='RBAC.User', verbose_name='用户'),
        ),
    ]
